name: build
on: [pull_request]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: mkdir --parents release/obj/
      - run:  mkdir --parents debug/obj/
      - run: sudo apt-get install libpng-dev libx11-dev
      - run: ls -la
      - run: make -k
      - run: make install