name: build
on: [pull_request]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - run: pwd
      - run: ls -la
      - run: make -k
      - run: make install